import argparse
import yaml
import textwrap
import inflection
from typing import Dict, List, TextIO, Union
from pydantic import BaseModel, PrivateAttr


class Enum (BaseModel):
    name: str
    values: List[str]


class Constant (BaseModel):
    name: str
    value: Union[int, str]


class Outputer (BaseModel):
    path: str
    _output: TextIO = PrivateAttr()
    _comment_mark: str = PrivateAttr()

    def __init__(self, *args, comment_mark="#", **kwargs):
        super().__init__(*args, **kwargs)
        self._output = open(self.path, "w")
        self._comment_mark = comment_mark
    
    def __del__(self):
        self._output.close()

    def output_enum(self, enum: Enum, prefix="", assignment="=", suffix=""):
        for (i, value) in enumerate(enum.values):
            self._output.write(f"{prefix}{value} {assignment} {i}{suffix}\n")

    def output_comment(self, comment):
        self._output.write(f"\n{self._comment_mark} {comment}\n")
    
    def output_constant(self, constant: Constant, prefix="", assignment="=", suffix=""):
        if type(constant.value) == int:
            value = constant.value
        elif type(constant.value) == str:
            value = f'"{constant.value}"'
        else:
            raise Exception("Internal error - illegal constant type. %s", type(constant.value))
        self._output.write(f"{prefix}{constant.name} {assignment} {value}{suffix}\n")

    def output_header(self):
        self._output.write(f"{self._comment_mark} autogenerated by reconstant - do not edit!\n")

    def output_footer(self):
        pass


class Python2Outputer (Outputer):

    def output_enum(self, constant : Constant):
        super().output_enum(constant, prefix=f"{inflection.underscore(constant.name).upper()}_")


class Python3Outputer (Outputer):
        
    def output_header(self):
        super().output_header()
        self._output.write("from enum import Enum\n")

    def output_enum(self, enum : Enum):
        self._output.write(f"class {enum.name}(Enum):\n")
        super().output_enum(enum, prefix=f"\t")
        self._output.write(f"\n")


class JavascriptOutputer (Outputer):

    def __init__(self, *args, **kwargs):
        super().__init__(comment_mark="//", *args, **kwargs)

    def output_enum(self, enum : Enum):
        self._output.write(f"export const {enum.name} = {{\n")
        super().output_enum(enum, prefix=f"\t", assignment=":", suffix=",")
        self._output.write(f"}}\n")

    def output_constant(self, constant: Constant):
        return super().output_constant(constant, prefix="export const ")


class COutputer (Outputer):

    def __init__(self, *args, **kwargs):
        super().__init__(comment_mark="//", *args, **kwargs)

    def output_header(self):
        super().output_header()
        guard_name = self._get_guard_name()
        self._output.write(textwrap.dedent(f"""\
            #ifndef {guard_name}
            #define {guard_name}
            """))

    def output_footer(self):
        super().output_footer()
        guard_name = self._get_guard_name()
        self._output.write(f"\n#endif /* {guard_name} */")

    def _get_guard_name(self):
        return self.path.replace('/', '_').replace(".", "_").upper()

    def output_enum(self, enum : Enum):
        self._output.write(f"typedef enum {{ {', '.join([val for val in enum.values])} }} {enum.name};\n")

    def output_constant(self, constant: Constant):
        name = inflection.underscore(constant.name).upper()
        if type(constant.value) == str:
            self._output.write(f'const char* {name} = "{constant.value}";\n')
        else:
            self._output.write(f'const {type(constant.value).__name__} {name} = {constant.value};\n')


# idea from https://stackoverflow.com/a/65734013/495995
class VueMixinOutputer (JavascriptOutputer):

    def output_enum(self, enum : Enum):
        super().output_enum(enum)
        name = enum.name
        self._output.write(textwrap.dedent(f"""\
            
            {name}.Mixin = {{
              created () {{
                  this.{name} = {name}
              }}
            }}
            """))


class AllOutputs (BaseModel):
    python: Python3Outputer = None
    python2: Python2Outputer = None
    javascript: JavascriptOutputer = None
    vue: VueMixinOutputer = None
    c: COutputer = None


class RootConfig (BaseModel):
    enums : List[Enum] = []
    constants : List[Constant] = []
    outputs: AllOutputs


def process_input(config: RootConfig):
    outputers = [getattr(config.outputs, x) for x in config.outputs.__fields_set__]

    for outputer in outputers:
        outputer.output_header()
        outputer.output_comment("constants")
        for constant in config.constants:
            outputer.output_constant(constant)
        outputer.output_comment("enums")
        for enum in config.enums:
            outputer.output_enum(enum)
        outputer.output_footer()
    

def main():
    parser = argparse.ArgumentParser(description='Reconstant - Share constant definitions between programming languages and make your constants constant again.')
    parser.add_argument('input', type=str, help='input file in yaml format')
    args = parser.parse_args()

    with open(args.input, "r") as yaml_input:
        python_obj = yaml.safe_load(yaml_input)
        config = RootConfig.parse_obj(python_obj)
        process_input(config)

if __name__ == "__main__":
    main()