// autogenerated by reconstant - do not edit!

// constants
pub const SOME_CONSTANT: &str = "this is a constant string";
pub const OTHER_CONSTANT: i32 = 42;

// enums
pub enum SomeEnum {
	A, 
	B, 
	C
}
pub enum OtherEnum {
	FOO, 
	BAR
}
