// autogenerated by reconstant - do not edit!

// this common comment will appear in all output files
// delete it from the yaml file if you don't need a common comment
#ifndef AUTOGENERATED_EXAMPLES_CONSTANTS_H
#define AUTOGENERATED_EXAMPLES_CONSTANTS_H

// constants
const char* SOME_CONSTANT = "this is a constant string";
const int OTHER_CONSTANT = 42;

// enums
typedef enum { A, B, C } SomeEnum;
typedef enum { FOO, BAR } OtherEnum;

#endif /* AUTOGENERATED_EXAMPLES_CONSTANTS_H */