# autogenerated by reconstant - do not edit!
from enum import IntEnum

# constants
SOME_CONSTANT = "this is a constant string"
OTHER_CONSTANT = 42

# enums
class SomeEnum(IntEnum):
	A = 0
	B = 1
	C = 2

class OtherEnum(IntEnum):
	FOO = 0
	BAR = 1

