// autogenerated by reconstant - do not edit!

// this common comment will appear in all output files
// delete it from the yaml file if you don't need a common comment

// constants
pub const SOME_CONSTANT: &str = "this is a constant string";
pub const OTHER_CONSTANT: i32 = 42;

// enums
pub enum SomeEnum {
	A, 
	B, 
	C
}
pub enum OtherEnum {
	FOO, 
	BAR
}
