// autogenerated by reconstant - do not edit!
#ifndef AUTOGENERATED_EXAMPLES_CONSTANTS_H
#define AUTOGENERATED_EXAMPLES_CONSTANTS_H

// constants
const char* SOME_CONSTANT = "this is a constant string";
const int OTHER_CONSTANT = 42;

// enums
typedef enum { A, B, C } SomeEnum;
typedef enum { FOO, BAR } OtherEnum;

#endif /* AUTOGENERATED_EXAMPLES_CONSTANTS_H */