# autogenerated by reconstant - do not edit!

# this common comment will appear in all output files
# delete it from the yaml file if you don't need a common comment

# constants
SOME_CONSTANT = "this is a constant string"
OTHER_CONSTANT = 42

# enums
SOME_ENUM_A = 0
SOME_ENUM_B = 1
SOME_ENUM_C = 2
OTHER_ENUM_FOO = 0
OTHER_ENUM_BAR = 1
