// autogenerated by reconstant - do not edit!

	// this common comment will appear in all output files
	// delete it from the yaml file if you don't need a common comment
public final class Constants {

	// constants
	public static final String SOME_CONSTANT = "this is a constant string";
	public static final int OTHER_CONSTANT = 42;

	// enums
	public enum SomeEnum {
		A, 
		B, 
		C
	}
	public enum OtherEnum {
		FOO, 
		BAR
	}

}