// autogenerated by reconstant - do not edit!
library constants;


// constants
const someConstant = "this is a constant string";
const otherConstant = 42;

// enums
enum SomeEnum {
  a,
  b,
  c
}
enum OtherEnum {
  foo,
  bar
}
