# autogenerated by reconstant - do not edit!

# this common comment will appear in all output files
# delete it from the yaml file if you don't need a common comment
from enum import Enum

# constants
SOME_CONSTANT = "this is a constant string"
OTHER_CONSTANT = 42

# enums
class SomeEnum(int, Enum):
	A = 0
	B = 1
	C = 2

class OtherEnum(int, Enum):
	FOO = 0
	BAR = 1

